---
  - name: Transfer and execute a script.
    hosts: appservers
    remote_user: ec2-user
    become: yes
    tasks:
        - name: Copy and Execute the shell script
          script: /home/ubuntu/userscript.sh
        - name: Copy file
          copy: src=/home/ubuntu/python1.py dest=/home/ec2-user/python1.py owner=ec2-user group=ec2-user mode=755
        - name: Execute script
          command: /usr/bin/python /home/ec2-user/python1.py
